# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
pod ‘IQKeyboardManager’
target 'PYlabelzishiying' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PYlabelzishiying

  target 'PYlabelzishiyingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PYlabelzishiyingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
